CHAT_LINK = "https://t.me/+dsgHgrwid_diNDQx"

CARDS_FOLDER = "cards"
CARDS2_FOLDER = "cards_2"
ARTIFACT_PRICE = 300
ARTIFACTS_FOLDER = "artifacts"
BATTLE_LIMIT = 7
MAX_NICK_LENGTH = 15
PACK_PRICE = 100

ADMIN_ID = 1630911435  # твой Telegram ID

DONATE_PHONE = "89155276176"
DONATE_BANKS = "Озон / Альфа"
DONATE_ADMIN_USERNAME = "@danikqk"
AKATSUKI_PRICE_RUB = 80
AKATSUKI_FOLDER = "card_akatsuki"
CHUNIN_PRICE_RUB = 60
BIJU_PRICE_RUB = 200
CHUNIN_FOLDER = "card_chunin"
BIJU_FOLDER = "card_biju"