services:
  - type: web
    name: naruto-card-bot
    env: python
    runtime: python3
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true
    envVars:
      - key: TOKEN
        sync: false
